appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ZT5PQsFmmHYjhpJCLLaJFO63onhTWXEY1Vhw6DQiddWKldddScLT9HaDyQrxpKsQ5CmbZi1wUNp7SjXBAUGxzMDodA6/ur7pvrd8iDsImPYbhleDpQPPJToLA51SLgzfns1dIZjUs6xgDONSmwjElms0cHT2iyu9PWK8QAFzr75Ww4MFzAbm9o8iFXVs75lqPz61QK03bY4b3CIgsz51HJLuR9wlCJr6CMRVhWkKdxGFyx00Yxq6zPP859NMJjRgTG5Kn03yAMDd9QwOwTIf4kGAlYcgZBVKTUgY23O0CjuZcxQ/nJ9lt+iKxLVzMriQ3h2+mc4B/4vBOhHXflP0DhMhzYYLCucKACr19T7Q1BUatbGZUwbCV3UHrWyVn0sbU9o4fZvNj0djKQ9e8+MDv2ERdUFQwVR5owMXallcI9J3HbxQHAQLiGLYiJVZX1xGcvQWgzItz4R3TEuy8mE8z3siFOYUnrRX5uMUSqKXAJXXXCxRmfaz/VKHz/U6Sm3Nd0Q4bCxCcHYh24dQDkN/NyFiooYz4aJEg1pymBA1vlphwDdgVNxKa5Jhv8Eq4T5cu2d/tx8pfXzlgbAKPAZzMoUqt0JraSx94NQXHZPDUqcLCxWE5y9DW1lhLMTNd6qlNffwuwHiMy+L2HgAJwQRNyzUzvGwP3O1Ba3q/70IhWs=}
provider:
  win: azure
bot:
  automerge: true
